apiVersion: v1
kind: Service
metadata:
  name: actions-docker-aks-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8090
      name: port80
      port: 8090
      protocol: TCP
  selector:
    app: actions-docker-aks
